# Generated by Django 4.0.5 on 2022-06-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library_model',
            old_name='address',
            new_name='Bookauthor',
        ),
        migrations.RenameField(
            model_name='library_model',
            old_name='name',
            new_name='Bookname',
        ),
        migrations.RenameField(
            model_name='library_model',
            old_name='age',
            new_name='Booknumber',
        ),
        migrations.RemoveField(
            model_name='library_model',
            name='bno',
        ),
    ]
